### PR TITLE
added option to not show the alert dialog that the icon changed

### PR DESCRIPTION
**Pull request by Flucadetena**
This is the only way I found to not show the alert in Objective C. I added the option from flutter so the developer can choose wether or not s/he wants to show it.

I couldn't find a way to send a bool through the invoke method, that is why i did it as a string. Maybe you know a better way.

For all I've seen this won't get your app rejected by the app store review. But I left the option in case someone faces the issue and can easily change it back to the basic configuration.

### CODE REVIEW

**Comment by tastelessjolt** [comment]
That's great. But it seems to use an undocumented API for changing the icon though. 
Btw, I hope you can add a reference to the original code if it was borrowed. Thank you!

Nevertheless better to have an option for the developer. 
I'll make it a boolean and also add a notice regarding the use of undocumented API. 
I'll make it opt-in for not showing alert and keep the default to `showAlert = true`.

**Comment by Flucadetena** [comment]
Hi! That is great, I agree with everything.

The code came from a Stackoverflow answer:

https://stackoverflow.com/questions/43356570/alternate-icon-in-ios-10-3-avoid-notification-dialog-for-icon-change/49730130#49730130

If I can helo with anything else let me know. And thanks for the great plugin

**Comment by Flucadetena** [comment]
Hey any updates on this?? Would love to go back to use the main link in pub for the package.

Also added a comment on the readme about the issue importing the assets, as i faced it and solve it with and answer you already had on the "issues" section. And credited the guay that gave the solution.

If you want I can add in the readme all the comment about hidden the dialog.

Thanks again for the package, really great :)

**Comment by tastelessjolt** [comment]
Hey, really sorry, I've been busy and didn't have access to a Mac. I'll merge and publish the PR this weekend. Thanks a lot for contributing.

**Comment by Flucadetena** [comment]
No worries man. We are all busy. That's amazing!! Thanks a lot for the hard work. If I can contribute with anything else please let me know.

**Comment by tastelessjolt** [comment]
Hey, @Flucadetena, thanks a lot for making the PR. I was having problems with my Mac, just fixed it and the new version with this will be live soon.

**Comment by Flucadetena** [comment]
Awesome!! Thanks @tastelessjolt very happy to hear that! Looking forward to it.

**Pull request merged**
